version: '3.8'
services:
  backend:
    container_name: backend-veterinary
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - db
    #volumes:
    #- .:.
  db:
    image: mongo
    container_name: db-veterinary
    restart: always
    ports:
      - '27017:27017'
